version: '3.7'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./data:/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=immachangethislaterlol
    ports:
      - "3000:3000"

volumes:
  grafana-storage:
